# Change these first
owner: adadaptedinc # Your GitHub username
repo: upptime # Your Github repository name

# Add your sites here
sites:
  - name: AdAdapted Direct
    url: https://direct.adadapted.dev
  - name: AdAdapted Circulars
    url: https://circulars.adadapted.dev
  - name: AdAdapted Direct Reporting API
    url: $DIRECT_REPORTING_API
  - name: AdAdapted Direct Service API
    url: $DIRECT_SERVICE_API
  - name: Circular API
    url: $CIRCULAR_API
  - name: Telemetry API
    url: $TELEMETRY_API

notifications:
  - type: slack
    channel: upttime-dev
status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.adadapted.dev
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [Github repository](https://github.com/koj-co/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/koj-co/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
